### ISSUE TITLE
how to show top bar in hours format in Gantt chart

### ISSUE THREAD

**Issue by NabeelMYousuf** [worktile/ngx-gantt#298]

**Comment by walkerkay** [comment]
I think the customized view can solve your problem
for reference example:

http://gantt.ngnice.com/components/custom-view
https://github.com/worktile/ngx-gantt/tree/master/example/src/app/gantt-custom-view
Because the minimum unit before is day, the dragging of the minute view may be affected, and we may improve this in the future

**Comment by UIJ5SZH** [comment]
Could you please give a demo for hours format in a day in Gantt chart? That's to say add a hour view type, thanks very much.
